.TH RECPERMISSIONS 1 2018\-10\-28
.SH NAME

.B RecPermissions:
Borra ficheros o directorios innecesarios, que tengan un patr\('on de fecha y hora en el directorio actual.
.SH SYNOPSIS

RecPermissions usage: recpermissions [\-h] [\-\-version] [\-\-user USER] [\-\-group GROUP]
                      [\-\-files FILES] [\-\-directories DIRECTORIES]
                      [\-\-remove_empty_directories]
.SH DESCRIPCI\('ON

.PP
Esta aplicaci\('on tiene los siguientes par\('ametros obligatorios
.PP
.RS
.B \-\-user
.RE
.PP
.RS
.RS
Usuario usado para cambiar el propietario de los ficheros
.RE
.RE
