.TH RECPERMISSIONS 1 2018\-10\-28
.SH NAME

.B RecPermissions:
Change files and directories owner and permissions recursively.
.SH SYNOPSIS

RecPermissions usage: recpermissions [\-h] [\-\-version] [\-\-user USER] [\-\-group GROUP]
                      [\-\-files FILES] [\-\-directories DIRECTORIES]
                      [\-\-remove_empty_directories] path
.SH DESCRIPTION

.PP
This app has the following mandatory parameters:
.PP
.RS
.B \-\-user
.RE
.PP
.RS
.RS
User used to change files owner.
.RE
.RE
.PP
.RS
.B \-\-group
.RE
.PP
.RS
.RS
Group used to change files owner group.
.RE
.RE
.PP
.RS
.B \-\-files
.RE
.PP
.RS
.RS
File permissions in octal to be used. 644 by default.
.RE
.RE
.PP
.RS
.B \-\-directories
.RE
.PP
.RS
.RS
Directory permissions in octal to be used. 755 by default.
.RE
.RE
.PP
.RS
.B \-\-remove_emptydirs
.RE
.PP
.RS
.RS
When used in script, removes all empty dirs recursively from path.
.RE
.RE
.PP
.RS
.B absolute_path
.RE
.PP
.RS
.RS
To avoid errors and wrong changes, path must be an absolute one.
.RE
.RE
